/** BCP-47 tags Warrden stores in `subtitle.languages` and writes on disk.
 * Primary subtags are the ISO 639-1 set; `zh-Hans` / `zh-Hant` are the script
 * variants the design uses. Not 639-2/T (`jpn`, `zho`).
 */
export const CATALOG: readonly { tag: string; name: string }[] = [
  { tag: 'aa', name: 'Afar' },
  { tag: 'ab', name: 'Abkhazian' },
  { tag: 'ae', name: 'Avestan' },
  { tag: 'af', name: 'Afrikaans' },
  { tag: 'ak', name: 'Akan' },
  { tag: 'am', name: 'Amharic' },
  { tag: 'an', name: 'Aragonese' },
  { tag: 'ar', name: 'Arabic' },
  { tag: 'as', name: 'Assamese' },
  { tag: 'av', name: 'Avaric' },
  { tag: 'ay', name: 'Aymara' },
  { tag: 'az', name: 'Azerbaijani' },
  { tag: 'ba', name: 'Bashkir' },
  { tag: 'be', name: 'Belarusian' },
  { tag: 'bg', name: 'Bulgarian' },
  { tag: 'bi', name: 'Bislama' },
  { tag: 'bm', name: 'Bambara' },
  { tag: 'bn', name: 'Bengali' },
  { tag: 'bo', name: 'Tibetan' },
  { tag: 'br', name: 'Breton' },
  { tag: 'bs', name: 'Bosnian' },
  { tag: 'ca', name: 'Catalan' },
  { tag: 'ce', name: 'Chechen' },
  { tag: 'ch', name: 'Chamorro' },
  { tag: 'co', name: 'Corsican' },
  { tag: 'cr', name: 'Cree' },
  { tag: 'cs', name: 'Czech' },
  { tag: 'cu', name: 'Church Slavic' },
  { tag: 'cv', name: 'Chuvash' },
  { tag: 'cy', name: 'Welsh' },
  { tag: 'da', name: 'Danish' },
  { tag: 'de', name: 'German' },
  { tag: 'dv', name: 'Divehi' },
  { tag: 'dz', name: 'Dzongkha' },
  { tag: 'ee', name: 'Ewe' },
  { tag: 'el', name: 'Greek' },
  { tag: 'en', name: 'English' },
  { tag: 'eo', name: 'Esperanto' },
  { tag: 'es', name: 'Spanish' },
  { tag: 'et', name: 'Estonian' },
  { tag: 'eu', name: 'Basque' },
  { tag: 'fa', name: 'Persian' },
  { tag: 'ff', name: 'Fulah' },
  { tag: 'fi', name: 'Finnish' },
  { tag: 'fj', name: 'Fijian' },
  { tag: 'fo', name: 'Faroese' },
  { tag: 'fr', name: 'French' },
  { tag: 'fy', name: 'Western Frisian' },
  { tag: 'ga', name: 'Irish' },
  { tag: 'gd', name: 'Scottish Gaelic' },
  { tag: 'gl', name: 'Galician' },
  { tag: 'gn', name: 'Guarani' },
  { tag: 'gu', name: 'Gujarati' },
  { tag: 'gv', name: 'Manx' },
  { tag: 'ha', name: 'Hausa' },
  { tag: 'he', name: 'Hebrew' },
  { tag: 'hi', name: 'Hindi' },
  { tag: 'ho', name: 'Hiri Motu' },
  { tag: 'hr', name: 'Croatian' },
  { tag: 'ht', name: 'Haitian' },
  { tag: 'hu', name: 'Hungarian' },
  { tag: 'hy', name: 'Armenian' },
  { tag: 'hz', name: 'Herero' },
  { tag: 'ia', name: 'Interlingua' },
  { tag: 'id', name: 'Indonesian' },
  { tag: 'ie', name: 'Interlingue' },
  { tag: 'ig', name: 'Igbo' },
  { tag: 'ii', name: 'Sichuan Yi' },
  { tag: 'ik', name: 'Inupiaq' },
  { tag: 'io', name: 'Ido' },
  { tag: 'is', name: 'Icelandic' },
  { tag: 'it', name: 'Italian' },
  { tag: 'iu', name: 'Inuktitut' },
  { tag: 'ja', name: 'Japanese' },
  { tag: 'jv', name: 'Javanese' },
  { tag: 'ka', name: 'Georgian' },
  { tag: 'kg', name: 'Kongo' },
  { tag: 'ki', name: 'Kikuyu' },
  { tag: 'kj', name: 'Kuanyama' },
  { tag: 'kk', name: 'Kazakh' },
  { tag: 'kl', name: 'Kalaallisut' },
  { tag: 'km', name: 'Khmer' },
  { tag: 'kn', name: 'Kannada' },
  { tag: 'ko', name: 'Korean' },
  { tag: 'kr', name: 'Kanuri' },
  { tag: 'ks', name: 'Kashmiri' },
  { tag: 'ku', name: 'Kurdish' },
  { tag: 'kv', name: 'Komi' },
  { tag: 'kw', name: 'Cornish' },
  { tag: 'ky', name: 'Kyrgyz' },
  { tag: 'la', name: 'Latin' },
  { tag: 'lb', name: 'Luxembourgish' },
  { tag: 'lg', name: 'Ganda' },
  { tag: 'li', name: 'Limburgan' },
  { tag: 'ln', name: 'Lingala' },
  { tag: 'lo', name: 'Lao' },
  { tag: 'lt', name: 'Lithuanian' },
  { tag: 'lu', name: 'Luba-Katanga' },
  { tag: 'lv', name: 'Latvian' },
  { tag: 'mg', name: 'Malagasy' },
  { tag: 'mh', name: 'Marshallese' },
  { tag: 'mi', name: 'Maori' },
  { tag: 'mk', name: 'Macedonian' },
  { tag: 'ml', name: 'Malayalam' },
  { tag: 'mn', name: 'Mongolian' },
  { tag: 'mr', name: 'Marathi' },
  { tag: 'ms', name: 'Malay' },
  { tag: 'mt', name: 'Maltese' },
  { tag: 'my', name: 'Burmese' },
  { tag: 'na', name: 'Nauru' },
  { tag: 'nb', name: 'Norwegian Bokmål' },
  { tag: 'nd', name: 'North Ndebele' },
  { tag: 'ne', name: 'Nepali' },
  { tag: 'ng', name: 'Ndonga' },
  { tag: 'nl', name: 'Dutch' },
  { tag: 'nn', name: 'Norwegian Nynorsk' },
  { tag: 'no', name: 'Norwegian' },
  { tag: 'nr', name: 'South Ndebele' },
  { tag: 'nv', name: 'Navajo' },
  { tag: 'ny', name: 'Chichewa' },
  { tag: 'oc', name: 'Occitan' },
  { tag: 'oj', name: 'Ojibwa' },
  { tag: 'om', name: 'Oromo' },
  { tag: 'or', name: 'Oriya' },
  { tag: 'os', name: 'Ossetian' },
  { tag: 'pa', name: 'Punjabi' },
  { tag: 'pi', name: 'Pali' },
  { tag: 'pl', name: 'Polish' },
  { tag: 'ps', name: 'Pashto' },
  { tag: 'pt', name: 'Portuguese' },
  { tag: 'qu', name: 'Quechua' },
  { tag: 'rm', name: 'Romansh' },
  { tag: 'rn', name: 'Rundi' },
  { tag: 'ro', name: 'Romanian' },
  { tag: 'ru', name: 'Russian' },
  { tag: 'rw', name: 'Kinyarwanda' },
  { tag: 'sa', name: 'Sanskrit' },
  { tag: 'sc', name: 'Sardinian' },
  { tag: 'sd', name: 'Sindhi' },
  { tag: 'se', name: 'Northern Sami' },
  { tag: 'sg', name: 'Sango' },
  { tag: 'si', name: 'Sinhala' },
  { tag: 'sk', name: 'Slovak' },
  { tag: 'sl', name: 'Slovenian' },
  { tag: 'sm', name: 'Samoan' },
  { tag: 'sn', name: 'Shona' },
  { tag: 'so', name: 'Somali' },
  { tag: 'sq', name: 'Albanian' },
  { tag: 'sr', name: 'Serbian' },
  { tag: 'ss', name: 'Swati' },
  { tag: 'st', name: 'Southern Sotho' },
  { tag: 'su', name: 'Sundanese' },
  { tag: 'sv', name: 'Swedish' },
  { tag: 'sw', name: 'Swahili' },
  { tag: 'ta', name: 'Tamil' },
  { tag: 'te', name: 'Telugu' },
  { tag: 'tg', name: 'Tajik' },
  { tag: 'th', name: 'Thai' },
  { tag: 'ti', name: 'Tigrinya' },
  { tag: 'tk', name: 'Turkmen' },
  { tag: 'tl', name: 'Tagalog' },
  { tag: 'tn', name: 'Tswana' },
  { tag: 'to', name: 'Tonga' },
  { tag: 'tr', name: 'Turkish' },
  { tag: 'ts', name: 'Tsonga' },
  { tag: 'tt', name: 'Tatar' },
  { tag: 'tw', name: 'Twi' },
  { tag: 'ty', name: 'Tahitian' },
  { tag: 'ug', name: 'Uyghur' },
  { tag: 'uk', name: 'Ukrainian' },
  { tag: 'ur', name: 'Urdu' },
  { tag: 'uz', name: 'Uzbek' },
  { tag: 've', name: 'Venda' },
  { tag: 'vi', name: 'Vietnamese' },
  { tag: 'vo', name: 'Volapük' },
  { tag: 'wa', name: 'Walloon' },
  { tag: 'wo', name: 'Wolof' },
  { tag: 'xh', name: 'Xhosa' },
  { tag: 'yi', name: 'Yiddish' },
  { tag: 'yo', name: 'Yoruba' },
  { tag: 'za', name: 'Zhuang' },
  { tag: 'zh', name: 'Chinese' },
  { tag: 'zh-Hans', name: 'Simplified Chinese' },
  { tag: 'zh-Hant', name: 'Traditional Chinese' },
  { tag: 'zu', name: 'Zulu' },
];
